/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LazerBasicCard {
        /**
          * image src
         */
        "cardImage": string;
        /**
          * Title
         */
        "cardTitle": string;
    }
    interface LazerButton {
        /**
          * Inner button text
         */
        "buttonText": string;
    }
    interface LazerCard {
        /**
          * Card date
         */
        "cardDate": string;
        /**
          * Card description
         */
        "cardDescription": string;
        /**
          * Card title
         */
        "cardTitle": string;
    }
    interface LazerRainbowCard {
        /**
          * image src
         */
        "cardImage": string;
        /**
          * Title
         */
        "cardTitle": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLLazerBasicCardElement extends Components.LazerBasicCard, HTMLStencilElement {
    }
    var HTMLLazerBasicCardElement: {
        prototype: HTMLLazerBasicCardElement;
        new (): HTMLLazerBasicCardElement;
    };
    interface HTMLLazerButtonElement extends Components.LazerButton, HTMLStencilElement {
    }
    var HTMLLazerButtonElement: {
        prototype: HTMLLazerButtonElement;
        new (): HTMLLazerButtonElement;
    };
    interface HTMLLazerCardElement extends Components.LazerCard, HTMLStencilElement {
    }
    var HTMLLazerCardElement: {
        prototype: HTMLLazerCardElement;
        new (): HTMLLazerCardElement;
    };
    interface HTMLLazerRainbowCardElement extends Components.LazerRainbowCard, HTMLStencilElement {
    }
    var HTMLLazerRainbowCardElement: {
        prototype: HTMLLazerRainbowCardElement;
        new (): HTMLLazerRainbowCardElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "lazer-basic-card": HTMLLazerBasicCardElement;
        "lazer-button": HTMLLazerButtonElement;
        "lazer-card": HTMLLazerCardElement;
        "lazer-rainbow-card": HTMLLazerRainbowCardElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface LazerBasicCard {
        /**
          * image src
         */
        "cardImage"?: string;
        /**
          * Title
         */
        "cardTitle"?: string;
    }
    interface LazerButton {
        /**
          * Inner button text
         */
        "buttonText"?: string;
        /**
          * Button click event
         */
        "onLazerButtonClickEvent"?: (event: CustomEvent<any>) => void;
    }
    interface LazerCard {
        /**
          * Card date
         */
        "cardDate"?: string;
        /**
          * Card description
         */
        "cardDescription"?: string;
        /**
          * Card title
         */
        "cardTitle"?: string;
    }
    interface LazerRainbowCard {
        /**
          * image src
         */
        "cardImage"?: string;
        /**
          * Title
         */
        "cardTitle"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "lazer-basic-card": LazerBasicCard;
        "lazer-button": LazerButton;
        "lazer-card": LazerCard;
        "lazer-rainbow-card": LazerRainbowCard;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lazer-basic-card": LocalJSX.LazerBasicCard & JSXBase.HTMLAttributes<HTMLLazerBasicCardElement>;
            "lazer-button": LocalJSX.LazerButton & JSXBase.HTMLAttributes<HTMLLazerButtonElement>;
            "lazer-card": LocalJSX.LazerCard & JSXBase.HTMLAttributes<HTMLLazerCardElement>;
            "lazer-rainbow-card": LocalJSX.LazerRainbowCard & JSXBase.HTMLAttributes<HTMLLazerRainbowCardElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
